### ISSUE TITLE
Memory requirements suddenly jump at large k-mer lengths

### ISSUE THREAD

**Issue by EricR86** [TravisWheelerLab/AvxWindowFmIndex#45]
I have been using the library for very long k-mer lengths (100kb or so) when I noticed that it was taking suddenly far more memory than expected. So I ran some tests only using the parallel count operation with a simple c program, checking on the maximum resident set size after completion:

For 10000 k-mers:
| bases | kilobytes |
|------|---------|
|10|3263432|
|100|3263512|
1000|3272816
10000|3390544
100000|4280780

For the last two k-lengths at 50000 k-mers:
bases| kilobytes
------|---------
10000|3907188
100000|8357388

I'm not sure what is happening in terms of sudden change in memory usage for these longer lengths and why the growth of memory seems to be significantly worse at longer lengths.

Any insight or help would be greatly appreciated.

Thanks!

**Comment by Sawwave** [comment]
If I'm understanding you correctly, I think the memory usage might be explained by the sheer number and size of your kmers. At 10,000 bases, 50,000 kmers should take up 10K*50K = 500MB, and at 100,000 bases, the same number of kmers should be 100K*50K = 5GB. 

The difference here is 5GB - 500MB = 4.5GB, which is roughly the size difference we see between 3,907,188K and 8,357,388K ( = 4450200K).

Does this sound like it explains the memory usage?

**Comment by EricR86** [comment]
You are very likely correct. I somehow was doing the same math by an order of magnitude off. Thanks!

**Comment by Sawwave** [comment]
happy to help!
