### ISSUE TITLE
Possible to use non-null terminated strings for sequence data?

### ISSUE THREAD

**Issue by EricR86** [TravisWheelerLab/AvxWindowFmIndex#47]
Is it possible to supply non-null terminated strings as sequence data for the parallel search?
In my rough testing it seems to segfault when attempting to dealloc the search list.

The reason for asking is each k-mer supplied is required to have it's own separate memory location as a null terminated string. If there's a giant buffer of sequence data, it would be far more convenient to have a way to supply an index/pointer to a location and a length to avoid allocating additional strings. Any insight or guidance would be greatly appreciated.

Thanks!

Eric

**Comment by Sawwave** [comment]
Also importantly, the dealloc function doesn't touch the kmers.

`void awFmDeallocKmerSearchList(struct AwFmKmerSearchList *_RESTRICT_ const searchList) {
	for(size_t i = 0; i < searchList->capacity; i++) {
		free(searchList->kmerSearchData[i].positionList);
	}
	free(searchList->kmerSearchData);
	free(searchList);
}`

A few situations I could imagine for segfaults during search list deallocation:

1. The searchList->capacity is increased, causing the first loop to go outside the allocated array.
2. The kmerSearchData was deallocated for some reason.
3. The searchList was already dealocated, and the function was called on unallocated memory.

Do any of these situations seem like they might be affecting you?

**Comment by EricR86** [comment]
Sorry yes you are correct. The segfault came from number of queries changing when I was quickly testing it out.

It's great to hear confirmation that kmerString does not require being null terminated however.

Sorry for the false report!

**Comment by Sawwave** [comment]
no worries, glad I could help!
